export const siteConfig = {
  name: 'Al Mashriq Medical Supplies',
  legalName: 'Al Mashriq Medical Supplies L.L.C',
  shortName: 'AMMS',
  url: 'https://ammsuae.me',
  title: 'Al Mashriq Medical Supplies (AMMS) | Leading Medical Equipment Supplier in UAE',
  description:
    'Premier UAE medical equipment distributor since 1991. AMMS supplies hospitals with world-class ICU, respiratory, anesthesia, and diagnostic solutions across Abu Dhabi and Dubai.',
  email: 'amms@eim.ae',
  phone: '+97126277223',
  displayPhone: '+971 2 627 7223',
  fax: '+97126271667',
  displayFax: '+971 2 627 1667',
  established: 1991,
  headOffice: {
    name: 'Head Office — Abu Dhabi',
    company: 'Al Mashriq Medical Supplies L.L.C',
    street: 'Floor 16-01, Falcon Tower, Qasr Al Hosn',
    poBox: 'PO Box 44800',
    city: 'Abu Dhabi',
    country: 'UAE',
    phone: '+971 2 627 7223',
    fax: '+971 2 627 1667',
    email: 'amms@eim.ae',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3631.4!2d54.3543!3d24.4539!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5e6561f4e6f9f1%3A0x8e97e7c3a0b5f4d8!2sFalcon%20Tower%2C%20Abu%20Dhabi!5e0!3m2!1sen!2sae!4v1700000000000!5m2!1sen!2sae',
  },
  branchOffice: {
    name: 'Branch Office — Dubai',
    company: 'Al Mashriq Medical Supplies L.L.C',
    street: 'Office 419, City 4 Building, Al Garhoud',
    poBox: 'PO Box 34570',
    city: 'Dubai',
    country: 'UAE',
    phone: '+971 4 282 7870',
    fax: '+971 4 282 7873',
    email: 'ammsd@ammsuae.com',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3609.8!2d55.3478!3d25.2491!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f5d4b0b8c1e5f%3A0x2e3c1d8f7a6b5c4d!2sAl%20Garhoud%2C%20Dubai!5e0!3m2!1sen!2sae!4v1700000000000!5m2!1sen!2sae',
  },
  address: {
    streetAddress: 'Floor 16-01, Falcon Tower, Qasr Al Hosn',
    locality: 'Abu Dhabi',
    region: 'Abu Dhabi',
    country: 'AE',
  },
  keywords: [
    'medical equipment UAE',
    'medical equipment supplier Abu Dhabi',
    'Al Mashriq Medical Supplies',
    'AMMS UAE',
    'hospital equipment UAE',
    'ICU equipment UAE',
    'respiratory care equipment UAE',
    'Fisher Paykel healthcare UAE',
    'CPAP machines UAE',
    'anesthesia equipment Abu Dhabi',
    'neonatal care equipment UAE',
    'medical consumables UAE',
    'healthcare equipment supplier UAE',
    'ventilator supplier UAE',
    'Penlon anesthesia UAE',
    'COSMED spirometry UAE',
  ],
  ogImage:
    'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1200&auto=format&fit=crop',
}

export const productCategories = [
  'Intensive Care Unit equipment',
  'Cardiac Care Unit equipment',
  'Surgical ICU equipment',
  'Neonatal ICU solutions',
  'Pediatric ICU solutions',
  'Operation Theatre equipment',
  'Cardiac Rehabilitation equipment',
  'Physiotherapy equipment',
  'Ophthalmic diagnostics',
  'Hearing diagnostics',
  'Respiratory & Sleep Apnea solutions',
  'Medical disposables and consumables',
  'Emergency medical products',
  'Cardiopulmonary equipment',
  'Homecare medical products',
]

export const principals = [
  {
    name: 'Fisher & Paykel Healthcare',
    slug: 'fisher-paykel',
    logo: '/images/clients/fisher-paykel.png',
    description: 'World-leading respiratory humidification and acute care solutions.',
    products: ['Respiratory Humidifiers', 'Breathing Circuits', 'Opti-flow Systems', 'Bubble CPAP Systems', 'Full Face & Nasal Masks', 'Infant Resuscitators (Neopuff)', 'Hospital & Home Masks'],
  },
  {
    name: 'Penlon',
    slug: 'penlon',
    logo: '/images/clients/penlon.png',
    description: 'Premium anesthesia delivery and airway management.',
    products: ['Anesthesia Machines', 'Air & Oxygen Flowmeters', 'Regulators', 'Bacteria Filters', 'Laryngoscopes', 'Suction Machines', 'Infusion Pumps', 'Syringe Pumps'],
  },
  {
    name: 'Breas',
    slug: 'breas',
    logo: '/images/clients/breas.png',
    description: 'Innovative ventilation and airway clearance solutions.',
    products: ['Bi-level Ventilators', 'Portable Ventilators', 'Airway Clearance Equipment'],
  },
  {
    name: 'COSMED',
    slug: 'cosmed',
    logo: '/images/clients/cosmed.png',
    description: 'Gold-standard metabolic testing and pulmonary function diagnostics.',
    products: ['Pulmonary Function Tests (PFTs)', 'QNRG Metabolic Testing', 'CPET Systems', 'Spirometry Equipment'],
  },
  {
    name: 'Baxter',
    slug: 'baxter',
    logo: '/images/clients/baxter.png',
    description: 'Advanced vision screening and ophthalmic diagnostic solutions.',
    products: ['Spot Vision Screener'],
  },
  {
    name: 'Sefam',
    slug: 'sefam',
    logo: '/images/clients/sefam.png',
    description: 'Comprehensive sleep apnea diagnosis and CPAP therapy.',
    products: ['CPAP Machines', 'Auto CPAP Machines', 'BiPAP Machines', 'Sleep Lab Systems', 'NightScan Screening', 'Masks'],
  },
  {
    name: 'Maxtec',
    slug: 'maxtec',
    logo: '/images/clients/maxtec.png',
    description: 'Precision oxygen analysis and flow measurement.',
    products: ['Oxygen Analyzers (15%–99%)', 'Flow Meters'],
  },
  {
    name: 'idmed',
    slug: 'idmed',
    logo: '/images/clients/idmed.png',
    description: 'Ophthalmic diagnostic innovation.',
    products: ['Ophthalmic Diagnostic Devices'],
  },
  {
    name: 'Bio-Med Devices',
    slug: 'bio-med',
    logo: '/images/clients/bio-med.png',
    description: 'Reliable air/oxygen blending and portable ventilation.',
    products: ['Air / O₂ Blenders', 'Portable Ventilators'],
  },
  {
    name: 'Porter',
    slug: 'porter',
    logo: '/images/clients/porter.png',
    description: 'The trusted name in nitrous oxide delivery systems.',
    products: ['Nitrous Oxide Systems — 50/50 Fixed', 'Adjustable 0–50% N₂O', 'Adjustable 0–70% N₂O'],
  },
]
